In [1]:
from PARCv2 import PARCv2
from Differentiator.Differentiator import Differentiator
from Differentiator.FiniteDifference import FiniteDifference
from Integrator.Integrator import Integrator
from Integrator.RK4 import RK4
import torch
from torchmetrics.functional.image import image_gradients

### Finite difference testing

In [7]:
right_diff = FiniteDifference(padding_mode="replicate")

In [8]:
image = torch.arange(0, 1*1*5*5, dtype=torch.float32)
image = torch.reshape(image, (1, 1, 5, 5))
dy, dx = image_gradients(image)
dy[0, 0, :, :]

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [0., 0., 0., 0., 0.]])

In [9]:
dx[0, 0, :, :]

tensor([[1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.]])

In [10]:
dy, dx = right_diff(image)
dy[0, 0, :, :]

tensor([[[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24.],
          [20., 21., 22., 23., 24.]]]])


tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [0., 0., 0., 0., 0.]])

In [11]:
dx[0, 0, :, :]

tensor([[1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0.]])